### ISSUE TITLE
More info on how to install and use TypeFly

### ISSUE THREAD

**Issue by nrlhozkan** [typefly/TypeFly#2]
Hello, Thank you for sharing the codes with us. 

Could you give more info on how to install and use TypeFly?

**Comment by Leonana69** [comment]
The general procedure is:
1. Setup environment variables: OPENAI_API_KEY, VISION_SERVICE_IP (where you run your Yolo service, set it as localhost if the Yolo runs on the same machine)
2. Setup the yolo service, you need to install the docker and Nvidia Container Toolkit.
3. Run Typefly webui, and open a web browser to access it.

**Comment by nrlhozkan** [comment]
Thank you for the information. Do we need a specific operating system like Ubuntu?

**Comment by nrlhozkan** [comment]
And I would like to use Tello edu instead of Tello that you used. Have you tested before with Tello Edu? I saw that you used sdk1 so it should be possible to use it without any changing because tello edu also uses sdk1.

**Comment by Leonana69** [comment]
I didn't test it with tello edu, but I think they have the same api. The code should just work with the Tello edu.

**Comment by yult0821** [comment]
> And I would like to use Tello edu instead of Tello that you used. Have you tested before with Tello Edu? I saw that you used sdk1 so it should be possible to use it without any changing because tello edu also uses sdk1.

@nrlhozkan  Hi, does Tello EDU work well with typefly? Looking forward to your reply, thanks very much!
