### ISSUE TITLE
Typefly doesn't work with the latest version of Webcolors (24.6.0)

### ISSUE THREAD

**Issue by nimo-labs** [typefly/TypeFly#3]
When using the latest version of Webcolors, Typefly fails with the error `AttributeError: module 'webcolors' has no attribute 'CSS3_HEX_TO_NAMES'` forcing Typefly to use V1.12 (by modifying install_requirements.sh)

**Comment by Leonana69** [comment]
I removed the use of webcolors since it's not a that crucial for our application.
