### ISSUE TITLE
Makefile still refers to virtual_cam

### ISSUE THREAD

**Issue by nimo-labs** [typefly/TypeFly#4]
The Makefile typefly target still uses the --use_virtual_cam parameter
`python3 ./serving/webui/typefly.py --use_virtual_cam`
It looks as though this should now be `--use_virtual_robot` instead.

**Comment by Leonana69** [comment]
Thanks, I'll update Readme later.

**Comment by nimo-labs** [comment]
Hi, It's not just the Readme, but the Makefile as well, resulting in an error when running `make typefly`

**Comment by Leonana69** [comment]
It's fixed now.
