### ISSUE TITLE
gear_wrapper tries to import Podtp which doens't exist.

### ISSUE THREAD

**Issue by nimo-labs** [typefly/TypeFly#5]
Line 4 of gear_wrapper.py `from podtp import Podtp` 
The Podtp doesn't appear to exist either within the project or pip.

**Comment by Leonana69** [comment]
This is for testing our own robot car. You can ignore that.

**Comment by nimo-labs** [comment]
@Leonana69 I did manage to ignore it by commenting out the import line, however, it does mean that by default, the application doesn't run without modification.
